### ISSUE TITLE
Missing New Line in "server-grbl.js"

### ISSUE THREAD

**Issue by DeadHunter** [openhardwarecoza/LaserWeb3#65]
Hi,
there is a missing new line in "server-grbl.js"

`$ node server-grbl.js
C:\LaserWeb3\server-grbl.js:28
var SerialPort = serialportvar
                 ^

ReferenceError: serialportvar is not defined
    at Object.<anonymous> (C:\LaserWeb3\server-grbl.js:28:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
`

**Comment by ghost** [comment]
Good catch! Fixed (:
