### ISSUE TITLE
LaserWeb3 crashing

### ISSUE THREAD

**Issue by trillerpfeife** [openhardwarecoza/LaserWeb3#66]
crashing with `node server-grbl.js`
using  commit 0509791
node version v4.4.7

``````
module.js:327
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/lila/github/LaserWeb3/config.js:1:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)```
``````

**Comment by ghost** [comment]
Did you remember 'npm install'?   Looks lime you dont have dotenv package installed from npm

**Comment by trillerpfeife** [comment]
thx
